### ISSUE TITLE
Try to get CI running on Windows

### ISSUE THREAD

**Issue by casey** [casey/degenerate#114]
It would be nice to support CI on Windows, just because there are so many Windows users out there. However, currently we have filenames which have `:` in them, which isn't supported on Windows. I don't know if it's worth it to fix. Maybe we could at least build on windows and run the unit tests, and just skip the image tests.

@terror Did we stop running CI on Windows for a specific reason? Or did we never try in the first place?

**Comment by terror** [comment]
Never tried because windows === trash

We should still try to get it working though, because inclusivity and all that

**Comment by casey** [comment]
I think as a first step, we should just figure out how to check out the repo on Windows. Maybe we could just not check out the `images` directory, which would just skip the image tests on Windows, but build everything else.
