### ISSUE TITLE
Examine pixel coordinate rounding behavior

### ISSUE THREAD

**Issue by terror** [casey/degenerate#125]
1. Using `round` which rounds away from zero, which is biased toward sampling out of bound pixels
2. Rounding each pixel x and y coordinate individually which might not give the same answer as finding the pixel with the shortest distance

**Comment by casey** [comment]
The rounding behavior is a little weird, but there isn't actually any observable problem with it. I'd be fine with just closing this, and reopening if we hit a bug or other issue. What do you think?

**Comment by casey** [comment]
Closing this, I think we're pretty convinced that this is fine at this point, and can always reopen if we see weird behavior.
