### ISSUE TITLE
Consider shell-like syntax

### ISSUE THREAD

**Issue by casey** [casey/degenerate#224]
The `:` separated syntax is nice for passing a program as arguments, but less nice for editing in the browser. We should consider a nicer, space-separated syntax.

Current syntax:
```
comment:slow seed:19798 rotate-color:g:0.01 rotate:0.01 for:100 random-mask apply loop rotate-color:b:0.01 rotate:0.01 for:100 random-mask apply loop save
```

Alternative, shell-like syntax:

```
# slow
seed 19798
rotate-color g 0.01
rotate 0.01
for 100
  random-mask
  apply
loop
rotate-color b 0.01
rotate 0.01
for 100
  random-mask
  apply
loop
save
````

**Comment by casey** [comment]
We could also avoid having to improve the language by embedding a [RustPython](https://github.com/RustPython/RustPython) interpreter and letting people use Python. Not sure what's best. I think having our own language is most aesthetic, but we might eventually have to add enough stuff, like functions, variables, scopes, types, etc, that we should consider using a language that already has these features.

**Comment by terror** [comment]
+1 for shell like syntax, looks pretty clean. 

Not sure if we're ever going to add those constructs, but if we do start supporting them we'll have to decide at what point does it become worthwhile to use rustpython or something.
