### ISSUE TITLE
missing field `wrap` at line 1

### ISSUE THREAD

**Issue by hacker-DOM** [casey/degenerate#480]
Default example gives

```
missing field `wrap` at line 1 column 383
missing field `wrap` at line 1 column 383
missing field `wrap` at line 1 column 383
missing field `wrap` at line 1 column 383...
```

Developer console shows

```
8x degenerate.js:729 missing field `wrap` at line 1 column 320
8x degenerate.js:729 missing field `wrap` at line 1 column 383
```

**Comment by casey** [comment]
Thanks for reporting this! Which example are you running, and what browser are you using? There's recently been a change to chrome that appears to be causing problems, so I'm wondering if that's related.
