### ISSUE TITLE
Add ability to give name to multiple filters and call them together

### ISSUE THREAD

**Issue by casey** [casey/degenerate#49]
I'm thinking something like:

```
save foo top square : foo foo
```

This would save `top square` to the name `foo`, and then call it twice, so it would be the same as calling:

```
top square top square
```

The syntax is definitely up for bikeshedding.

**Comment by terror** [comment]
So this would render the `save` command to have multiple use-cases? We could probably introduce a `bind` command instead, so save could be left for solely the saving of state on disk.

**Comment by casey** [comment]
> So this would render the save command to have multiple use-cases? We could probably introduce a bind command instead, so save could be left for solely the saving of state on disk.

Whoops, I forgot that `save` was already taken. Maybe the keyword should be `let`, since it's short and that's how you introduce a variable binding in rust.
