### ISSUE TITLE
Convert more tests to image tests

### ISSUE THREAD

**Issue by casey** [casey/degenerate#68]
What do you think about this? I'm leaning towards thinking we should do this. We can use higher resolution than is practical for text-based tests, and they serve as a form of documentation for what filters do.

**Comment by casey** [comment]
@terror

**Comment by terror** [comment]
Yep that sounds good, and since we're storing the images on GitHub we can also link them to the README as examples for each filter.

**Comment by casey** [comment]
I think this is basically done.
